#- platform: rest
#  resource: !secret teamwork_nv_tasks_url
#  name: tasks
#  authentication: basic
#  username: !secret teamwork_nv_auth
#  password: X
#  json_attributes:
#    - todo-items
#  value_template: 'OK'
#- platform: template
#  sensors:
#    todo_items:
#      value_template: '{{ states.sensor.tasks.attributes["todo-items"][0]["content"] }}'

# id = task number.
# project-id = project
# todo-list-id = task list

#- platform: template
#  sensors:
#    task_id:
#      value_template: '{{states.sensor.tasks.attributes["todo-items"]["id"]}}'
- platform: rest
  resource: !secret clickup_tasks_url
  name: tasks
  username: !secret clickup_user
  password: !secret clickup_password
  headers:
    Authorization: !secret clickup_token
    Content-Type: application/json
  json_attributes:
    - tasks

- platform: template
  sensors:
    task_name:
      value_template: '{{ states.sensor.clickuptasks.attributes["tasks"][0]["name"] }}'
