- id: '1601360255168'
  alias: Tag Jon's Tag is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: B9-E8-15-C9
  condition: []
  action:
  - service: media_player.volume_set
    data:
      volume_level: 0.8
    entity_id: media_player.spotify_jon_griffith
  - delay: '2'
  - service: media_player.play_media
    data:
      media_content_id: spotify:track:6twjbQiAbWOMUt4S8RoDbk
      media_content_type: music
    entity_id: media_player.spotify_jon_griffith
  - service: light.turn_on
    data:
      brightness: 255
    entity_id: light.workshop
  mode: single
- id: '1662012954121'
  alias: Task Notification
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.household
    attribute: items
  condition: []
  action:
  - service: notify.mobile_app_jon
    data:
      message: '{% set value_json = state_attr(''sensor.household'',''items'') %}
        {{value_json[0].content}}'
  mode: single
- id: '1662418108441'
  alias: Picore Down Idle 10m
  description: ''
  trigger:
  - platform: device
    device_id: bb7ea7d77012fca207408d1ef41a2950
    domain: media_player
    entity_id: media_player.picoreplayer
    type: idle
    for:
      hours: 0
      minutes: 10
      seconds: 0
  condition: []
  action:
  - service: media_player.volume_set
    data:
      volume_level: 0
    target:
      device_id: bb7ea7d77012fca207408d1ef41a2950
  mode: single
- id: '1662694234524'
  alias: Music in the Shower
  description: ''
  trigger:
  - platform: state
    entity_id:
    - climate.u_by_moen_012547
    from: 'off'
  condition: []
  action:
  - service: media_player.turn_on
    data: {}
    target:
      entity_id: media_player.mass_picoreplayer
  - service: media_player.volume_set
    data:
      volume_level: 0.7
    target:
      entity_id:
      - media_player.mass_picoreplayer
  - service: media_player.select_source
    data:
      source: http://192.168.1.101:8095/74648f7c9b7b49f1897d39f0899e454c.flac
    target:
      entity_id:
      - media_player.mass_picoreplayer
  mode: single
- id: '1662695081488'
  alias: Shower Off, Music Off
  description: ''
  trigger:
  - platform: state
    entity_id:
    - climate.u_by_moen_012547
    to: 'off'
  condition: []
  action:
  - service: media_player.media_stop
    data: {}
    target:
      entity_id: media_player.mass_picoreplayer
  - service: media_player.turn_off
    data: {}
    target:
      entity_id: media_player.mass_picoreplayer
  mode: single
