- id: '1678596717654'
  alias: Mount NAS Folder
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: shell_command.mount_nas_folder
  mode: single
- id: '1679193576671'
  alias: Restore Samba Backup Sensor
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: hassio.addon_stdin
    data:
      addon: 15d21743_samba_backup
      input: restore-sensor
  mode: single
- id: '1689559542401'
  alias: Bookstack Light Trigger
  description: ''
  trigger:
  - platform: webhook
    allowed_methods:
    - POST
    - PUT
    local_only: true
    webhook_id: -DeIxsmG4iJTTKNEdKjRz2x-Z
  condition: []
  action:
  - service: notify.mobile_app_jon
    data:
      message: '{{ state_attr(''sensor.legacy_wiki'',''description'') }}'
      title: Griffith Legacy Wiki Update
      data:
        actions:
        - action: Open Page
          title: Open Safari
          uri: '{{ state_attr(''sensor.legacy_wiki'',''url'') }}'
  - service: notify.mobile_app_melanie
    data:
      message: '{{ state_attr(''sensor.legacy_wiki'',''description'') }}'
      title: Griffith Legacy Wiki Update
      data:
        actions:
        - action: Open Page
          title: Open Safari
          uri: '{{ state_attr(''sensor.legacy_wiki'',''url'') }}'
  mode: single
