- id: '1678596717654'
  alias: Mount NAS Folder
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: shell_command.mount_nas_folder
  mode: single
- id: '1679193576671'
  alias: Restore Samba Backup Sensor
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: hassio.addon_stdin
    data:
      addon: 15d21743_samba_backup
      input: restore-sensor
  mode: single
