- id: '1591419330636'
  alias: New Automation
  description: Turn off Candle Warmer 1 at 23:59
  trigger:
  - at: '23:59'
    platform: time
  condition:
  - after: '23:59'
    before: 00:01
    condition: time
  action:
  - data: {}
    entity_id: switch.sonoff_candle_warmer_1
    service: switch.turn_off
- id: '1601360255168'
  alias: Tag Jon's Tag is scanned
  description: ''
  trigger:
  - platform: tag
    tag_id: B9-E8-15-C9
  condition: []
  action:
  - service: media_player.volume_set
    data:
      volume_level: 0.8
    entity_id: media_player.spotify_jon_griffith
  - delay: '2'
  - service: media_player.play_media
    data:
      media_content_id: spotify:track:6twjbQiAbWOMUt4S8RoDbk
      media_content_type: music
    entity_id: media_player.spotify_jon_griffith
  - service: light.turn_on
    data:
      brightness: 255
    entity_id: light.workshop
  mode: single
