# Configure a default setup of Home Assistant (frontend, api, etc)
homeassistant:
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.214
        - 192.168.1.219
        - 192.168.1.145
        - 192.168.1.242
        - 192.168.1.45
        - 192.168.1.35
        - 192.168.1.132
      allow_bypass_login: false
    - type: homeassistant
# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123
# The following section is provided to ensure functionality due to reverse proxy settings on the Apache server at 192.168.1.110
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.1.200
  ip_ban_enabled: false
  login_attempts_threshold: 5
api:
# Text to speech
#tts:
#  - platform: microsoft
#    api_key: !secret microsoft_tts
#    language: en-au
#    gender: Male
#    type: Catherine
#    region: westus2
#    base_url: https://ha.jongriffith.com

#- platform: google_translate
#  cache: true
#  cache_dir: /tmp/tts
#  time_memory: 300
#  base_url: https://hassio.jongriffith.com:8123
#  service_name: google_translate_say

automation: !include automations.yaml
binary_sensor: !include_dir_merge_list integrations/binary_sensors/
camera: !include_dir_merge_list integrations/camera/
counter: !include_dir_merge_named integrations/counters/
device_tracker: !include_dir_merge_list integrations/device_tracker/
google: !include_dir_merge_named integrations/google/
history:
  exclude:
    domains:
      - automation
      - updater
      - calendar
      - camera
      - device_tracker
influxdb: !include_dir_merge_named integrations/influxdb/
input_boolean: !include_dir_merge_named integrations/input_boolean/
input_datetime: !include_dir_merge_named integrations/input_datetime/
input_number: !include_dir_merge_named integrations/input_number/
input_select: !include_dir_merge_named integrations/input_select/
light: !include_dir_merge_list integrations/lights/ # Light Switches
life360:
  circles:
    exclude:
      - "Family"
  show_as_state:
    - driving
    - moving
mqtt: !include_dir_merge_named integrations/mqtt/ #MQTT Server on Ubuntu
media_player: !include_dir_merge_list integrations/media_players/
neato: !include_dir_merge_named integrations/robots/ # Botvac
notify: !include_dir_merge_list integrations/notify/
octoprint: !include_dir_merge_named integrations/octoprint/
proximity: !include_dir_merge_named integrations/proximity/
recorder: !include_dir_merge_named integrations/recorder/
spotify: !include_dir_merge_named integrations/spotify/
sensor: !include_dir_merge_list integrations/sensors/
#folder_watcher: !include_dir_merge_list integrations/folder_watcher/
scene: !include scenes.yaml
script: !include scripts.yaml
template: !include_dir_merge_list integrations/template/
twilio: !include_dir_merge_named integrations/twilio/
samsungtv: !include_dir_merge_list integrations/samsungtv/
wake_on_lan:
zone: !include_dir_merge_list zones/ # Zones
zoneminder: !include_dir_merge_list integrations/zoneminder/
#zwave: !include_dir_merge_named zwave/ # Zwave Config flig

stream:
discovery:
sun:
cloud:
wemo:
  discovery: false
  static:
    - 192.168.1.60 # Patio Lights
    - 192.168.1.61 # Entertainment Center
