# Configure a default setup of Home Assistant (frontend, api, etc)
homeassistant:
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.214
        - 192.168.1.219
        - 192.168.1.145
        - 192.168.1.242
        - 192.168.1.45
        - 192.168.1.35
        - 192.168.1.132
        - 192.168.1.191
        - 192.168.1.97
        - 192.168.2.188
        - 192.168.2.214
      allow_bypass_login: false
    - type: homeassistant
  customize: !include customize.yaml
frontend:
  extra_module_url:
    - /local/community/lovelace-card-mod/card-mod.js
    - /local/refresh.js
  themes: !include_dir_merge_named themes/
# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123
# The following section is provided to ensure functionality due to reverse proxy settings on the Apache server at 192.168.1.110
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.1.200
  ip_ban_enabled: false
  login_attempts_threshold: 5
api:

amcrest: !include_dir_merge_list integrations/amcrest/
automation: !include automations.yaml
binary_sensor: !include_dir_merge_list integrations/binary_sensors/
camera: !include_dir_merge_list integrations/camera/
calendar: !include_dir_merge_named integrations/calendar/
counter: !include_dir_merge_named integrations/counters/
device_tracker: !include_dir_merge_list integrations/device_tracker/
feedreader: !include_dir_merge_named integrations/feedreader/
group: !include_dir_merge_list integrations/group/
history:
  exclude:
    domains:
      - automation
      - updater
      - calendar
      - camera
      - device_tracker
input_boolean: !include_dir_merge_named integrations/input_boolean/
input_button: !include_dir_merge_named integrations/input_buttons/
input_datetime: !include_dir_merge_named integrations/input_datetime/
input_number: !include_dir_merge_named integrations/input_number/
input_select: !include_dir_merge_named integrations/input_select/
light: !include_dir_merge_list integrations/lights/ # Light Switches
#mqtt: !include_dir_merge_named integrations/mqtt/ #MQTT Server on Ubuntu
media_source:
my:
notify: !include_dir_merge_list integrations/notify/
proximity: !include_dir_merge_named integrations/proximity/
recorder: !include_dir_merge_named integrations/recorder/
rest_command: !include_dir_merge_named integrations/rest_command/
#spotify: !include_dir_merge_named integrations/spotify/
sensor: !include_dir_merge_list integrations/sensors/
#folder_watcher: !include_dir_merge_list integrations/folder_watcher/
scene: !include scenes.yaml
script: !include scripts.yaml
spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key
template: !include_dir_merge_list integrations/template/
timer: !include_dir_merge_named integrations/timers/
tts: !include_dir_merge_list integrations/tts/
# twilio: !include_dir_merge_named integrations/twilio/
# samsungtv: !include_dir_merge_list integrations/samsungtv/
# wake_on_lan:
zone: !include_dir_merge_list zones/ # Zones
#zoneminder: !include_dir_merge_list integrations/zoneminder/

ffmpeg:
logbook:
  include:
    domains:
      - light
stream:
discovery:
sun:
cloud:
wemo:
  discovery: true
shell_command:
  mount_nas_folder: mkdir -p /media/nasfiles;mount -t nfs4 192.168.1.140:/mnt/user/Media/Inbound/Scanner /media/nasfiles
ynab:
  api_key: !secret ynab_api_key
  name: "My YNAB Budget"
  currency: "$"
  accounts:
    - "Wells Personal Checking"
    - "Business Checking"
    - "Emergency Fund"
    - "Business Annual Expenses"
    - "Income Tax Savings"
    - "Remodeling Fund"
    - "Chateau De Vie Mortgage"
