- platform: switch
  name: Patio Lights
  entity_id: switch.patio_lights

- platform: switch
  name: Entertainment Center
  entity_id: switch.entertainment_center

- platform: switch
  name: Workshop Desk Lamp
  entity_id: switch.sonoff_desk_lamp_1