- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: disk_use
      arg: /    
    - type: memory_free
    - type: disk_free
      arg: /
    - type: memory_use_percent
    - type: memory_use

- platform: template
  sensors:
    hass_count:
      friendly_name: HASS Count
      icon_template: mdi:home-assistant
      value_template: "{{ states | count }}"
      attribute_templates:
        automation: "{{ states.automation | count }}"
        binary_sensor: "{{ states.binary_sensor | count }}"
        camera: "{{ states.camera | count }}"
        climate: "{{ states.climate | count }}"
        device_tracker: "{{ states.device_tracker | count }}"
        light: "{{ states.light | count }}"
        media_player: "{{ states.media_player | count }}"
        scene: "{{ states.scene | count }}"
        script: "{{ states.script | count }}"
        sensor: "{{ states.sensor | count }}"
        switch: "{{ states.switch | count }}"
        zwave: "{{ states.zwave | count }}"

- platform: sql
  db_url: !secret mysql_db_url
  queries:
    - name: DB Size
      query: 'SELECT table_schema "database", Round(Sum(data_length + index_length) / 1024, 1) "value" FROM information_schema.tables WHERE table_schema="hassio" GROUP BY table_schema;'
      column: 'value'
      unit_of_measurement: kB